--GROUP BY
--Q1 Count the number of orders for each OrderStatus
SELECT 
OrderStatus,
count(*) as totalorders
from sales.orders
group by OrderStatus

--Q2 Display each CustomerID along with the total sales generated by that customer.

select 
customerid,
sum(sales) as totalsales
from sales.orders
group by customerID
--Q3 Display each ProductID along with the average quantity ordered.
select 
productID,
avg(quantity) as averagequant
from sales.Orders
group by ProductID
--Q4 Display each SalesPersonID along with the highest sale they have made.

select 
salesPersonID,
max(sales) as highestsales
from sales.orders
group by salespersonid
/*Q5Display each OrderStatus along with:
Total number of orders
Total sales
Average sales*/
select 
orderstatus,

count(*) as total_orders,
sum(sales) as toatal_sales,
avg(sales) as avg_sales
from sales.orders
group by OrderStatus


--HAVING CALUSE
--Q1.Display customers whose total sales are greater than 100.

SELECT
    CustomerID,
    SUM(Sales) AS TotalSales
FROM sales.orders
GROUP BY CustomerID
HAVING SUM(Sales) > 100;
-- Q2.Display order statuses having more than 5 orders.

SELECT
    OrderStatus,
    COUNT(*) AS TotalOrders
FROM sales.orders
GROUP BY OrderStatus
HAVING COUNT(*) >= 5;